networks:
  default:
    external:
      name: load-testing-network

services:

  k6:
    container_name: k6
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./js:/k6-scripts
